### ISSUE TITLE
Menu: 'just-visited.failed' css animation not firing on 2nd and 3rd visit attempts

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#61] opened 2016-03-11 10:19 UTC
actually neither the 'attempting' animation, or the 'just-visited.failed' animation are firing on the 2nd and 3rd visit attempts

**Comment by mushon** [comment] 2016-03-18 09:55
as mentioned in #64 this is not a bug but a feature. Reassigning to close.

**Closed** 2016-03-18 10:22 UTC
Labels: Bug, PRIORITY: Low
